### ISSUE TITLE
Add basic authentication support to AuthorizationServer

### ISSUE THREAD

**Issue by bahrens** [DotNetOpenAuth/DotNetOpenAuth#105] opened 2012-03-29 17:21 UTC
OAuth 2.0 specification states in section 2.3.1 that clients should also be able to authenticate with the authorization server using basic authentication. Basic authentication is the recommended approach, rather than sending the client identifier and client secret in the body of the request.  Sending the client identifier and client secret is only recommended for clients unable to use basic authentication. Currently the AuthorizationServer does not support basic authentication.

**Comment by AArnott** [comment] 2012-04-01 16:33
Duplicate of #75

**Closed as completed by AArnott** 2012-04-01 16:33 UTC

**Comment by AArnott** [comment] 2012-04-21 02:43
Fixed by dd8ace7
