### ISSUE TITLE
LinkedIn client does not appear to work

### ISSUE THREAD

**Issue by tofutim** [DotNetOpenAuth/DotNetOpenAuth#237] opened 2012-11-28 03:27 UTC
I'm able to login, but when it redirects back to my site it fails. I think the problem happens somehow near base.WebWorker.PrepareAuthorizedRequest(profileEndpoint, accessToken)

**Comment by tofutim** [comment] 2012-11-28 03:28
Looks like some solutions are found here - https://github.com/DotNetOpenAuth/DotNetOpenAuth/issues/175 - has this been addressed with a pull request yet?

**Comment by AArnott** [comment] 2012-11-28 05:44
Duplicate of #232

**Closed as completed by AArnott** 2012-11-28 05:44 UTC
