### ISSUE TITLE
Discovered endpoint info: [] 

### ISSUE THREAD

**Issue by vijayasarathi** [DotNetOpenAuth/DotNetOpenAuth#303] opened 2013-08-20 11:32 UTC
The OpenID Provider issued an assertion for an Identifier whose discovery information did not match. 
Assertion endpoint info: 
ClaimedIdentifier: http://localhost/**_/OpenId/user/admin 
ProviderLocalIdentifier: http://localhost/**_/OpenId/user/admin  
ProviderEndpoint: http://localhost/***/openid/server 
OpenID version: 2.0 
Service Type URIs: 
Discovered endpoint info: [] 

I'm trying to create a OP using Dotnetopenauth. openid.GetResponse() is throwing the above error. The Discovered  endpoint info is blank. Kindly help me to resolve the issue.

**Comment by AArnott** [comment] 2013-10-15 02:48
Closing as this is not a bug in the library.
Please use the forums to ask for help.

**Closed as completed by AArnott** 2013-10-15 02:48 UTC
