### ISSUE TITLE
Upgrade log4net to 1.2.11.0

### ISSUE THREAD

**Issue by bloudraak** [DotNetOpenAuth/DotNetOpenAuth#144] opened 2012-05-14 00:15 UTC
Upgrade log4net to version 1.2.11.0.

**Comment by rcollette** [comment] 2012-07-08 14:58
Shouldn't this be closed for release 4.1?

**Comment by AArnott** [comment] 2012-11-12 04:54
Duplicate of #157

**Closed as completed** 2012-11-12 04:54 UTC
