### ISSUE TITLE
CultureNotFoundException

### ISSUE THREAD

**Issue by johnkamau** [DotNetOpenAuth/DotNetOpenAuth#273] opened 2013-04-23 13:22 UTC
During the authentication process, the code errors out with the exception, CultureNotFound.

_CultureNotFoundException
System.Globalization.CultureNotFoundException: Culture is not supported. Parameter name: name en-KE is an invalid culture identifier. at System.Globalization.CultureInfo.GetCultureInfo(String name) at DotNetOpenAuth.OpenId.Extensions.SimpleRegistration.ClaimsResponse.get_Culture() at ServiceStack.Authentication.OpenId.OpenIdExtensions.ToDictionary(ClaimsResponse response) at ServiceStack.Authentication.OpenId.OpenIdOAuthProvider.CreateAuthInfo(IAuthenticationResponse response) at ServiceStack.Authentication.OpenId.OpenIdOAuthProvider.Authenticate(IServiceBase authService, IAuthSession session, Auth request)_

While switching to en-Us etc may work, I still need it to work with my (and my users) default locale. Any work-around I can use for the moment?

**Comment by AArnott** [comment] 2013-04-26 04:08
Duplicate of #261

**Closed as completed by AArnott** 2013-04-26 04:08 UTC
