### ISSUE TITLE
Unsolicited Assertion: Protocol Error - OpenIdProvider.GetRequest is being called.

### ISSUE THREAD

**Issue by rcollette** [DotNetOpenAuth/DotNetOpenAuth#176] opened 2012-07-12 14:31 UTC
I am getting a protocol error in the logs when sending an unsolicited assertion.  The logged stack trace also seems to be missing the call to either OpenIdProvider.PrepareUnsolicitedAssertion or FetchResponse.Send

It seems like one of these two methods is assuming that the assertion is being sent in response to an authentication request, which is not the case for an unsolicited assertion.   Because the response is being prepared as an unsolicited assertion, there should be some indicator that should make the code skip OpenIdProvider.GetRequest().

This must be happening in a try/catch because my code continues to run successfully (the response is sent) despite this error being logged.   The fact the error is there just causes confusion when dealing with other developers, partners, etc.

Code and Provider Log follow:

``` C#
private void SendAssertion(string relyingPartyRealm)
{
    //We are explicitly telling the RP the URL to use for 
    Uri providerEndpoint = new Uri(Request.Url, Page.ResolveUrl("~/Provider.ashx"));
    OpenIdProvider op = new OpenIdProvider();
    try
    {
        // Send user input through identifier parser so we accept more free-form input.
        string rpSite = Identifier.Parse(relyingPartyRealm);
        IRequest pendingRequest = op.GetRequest();
        var fetchResponse = new FetchResponse();
        KeyedCollection<string, AttributeValues> attributes = fetchResponse.Attributes;
        attributes.Add(WellKnownAttributes.Contact.Email, "john_doe@acme.com");
        attributes.Add(WellKnownAttributes.Name.FullName,"John Doe");
        attributes.Add(WellKnownAttributes.Contact.HomeAddress.StreetAddressLine1, "1 Some St.");
        attributes.Add(WellKnownAttributes.Contact.HomeAddress.StreetAddressLine2, "Address Line2");
        attributes.Add(WellKnownAttributes.Contact.HomeAddress.City, "Enfield");
        attributes.Add(WellKnownAttributes.Contact.HomeAddress.State, "CT");
        attributes.Add(WellKnownAttributes.Contact.HomeAddress.PostalCode, "06082");
        attributes.Add(WellKnownAttributes.Person.Gender, "M");                
        OutgoingWebResponse response = op.PrepareUnsolicitedAssertion(providerEndpoint, rpSite, Util.BuildIdentityUrl(), Util.BuildIdentityUrl(), fetchResponse);
        response.Send();
    }
    catch (ProtocolException ex)
    {
        Label errorLabel = (Label)this.loginView.FindControl("errorLabel");
        errorLabel.Visible = true;
        errorLabel.Text = ex.Message;
    }
}
```

2012-07-12 09:47:29,060 (GMT-4) [5] DEBUG OpenIdProviderWebForms.Global - User IS authenticated.
2012-07-12 09:47:29,138 (GMT-4) [5] INFO  DotNetOpenAuth - DotNetOpenAuth, Version=4.1.0.12182, Culture=neutral, PublicKeyToken=2780ccd10d57b246 (official)
2012-07-12 09:47:29,138 (GMT-4) [5] DEBUG DotNetOpenAuth.OpenId - .NET Uri class path compression overridden.
2012-07-12 09:47:29,153 (GMT-4) [5] INFO  DotNetOpenAuth.Messaging.Channel - Scanning incoming request for messages: http://localhost:4860/Default.aspx
2012-07-12 09:47:29,153 (GMT-4) [5] DEBUG DotNetOpenAuth.Messaging.Channel - Incoming HTTP request: POST http://localhost:4860/Default.aspx
2012-07-12 09:47:29,153 (GMT-4) [5] ERROR DotNetOpenAuth.Messaging - Protocol error: Unexpected message type received.
   at DotNetOpenAuth.Messaging.ErrorUtilities.VerifyProtocol(Boolean condition, String unformattedMessage, Object[] args)
   at DotNetOpenAuth.Messaging.ErrorUtilities.ThrowProtocol(String unformattedMessage, Object[] args)
   at DotNetOpenAuth.OpenId.Provider.OpenIdProvider.GetRequest(HttpRequestBase httpRequestInfo)
   at DotNetOpenAuth.OpenId.Provider.OpenIdProvider.GetRequest()
   at OpenIdProviderWebForms._default.SendAssertion(String relyingPartyRealm)
   at OpenIdProviderWebForms._default.lnkRelyingParty_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.default_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
   at System.Web.HttpApplication.ApplicationStepManager.ResumeSteps(Exception error)
   at System.Web.HttpApplication.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpRuntime.ProcessRequestInternal(HttpWorkerRequest wr)
   at System.Web.HttpRuntime.ProcessRequestNoDemand(HttpWorkerRequest wr)
   at System.Web.HttpRuntime.ProcessRequest(HttpWorkerRequest wr)
   at Microsoft.VisualStudio.WebHost.Request.Process()
   at Microsoft.VisualStudio.WebHost.Host.ProcessRequest(Connection conn)

2012-07-12 09:47:29,169 (GMT-4) [5] ERROR DotNetOpenAuth.OpenId - An exception was generated while processing an incoming OpenID request.
DotNetOpenAuth.Messaging.ProtocolException: Unexpected message type received.
   at DotNetOpenAuth.Messaging.ErrorUtilities.VerifyProtocol(Boolean condition, String unformattedMessage, Object[] args)
   at DotNetOpenAuth.Messaging.ErrorUtilities.ThrowProtocol(String unformattedMessage, Object[] args)
   at DotNetOpenAuth.OpenId.Provider.OpenIdProvider.GetRequest(HttpRequestBase httpRequestInfo)

**Comment by AArnott** [comment] 2012-12-24 04:15
Your code snippet includes this line:
    IRequest pendingRequest = op.GetRequest();

Yet you don't do anything with `pendingRequest` afterward. This call is why you get the error in your logs. If you're sending an unsolicited assertion, this line does not belong in your method.

Closing as by design.

**Closed as completed by AArnott** 2012-12-24 04:15 UTC
