### ISSUE TITLE
CreateFormatter throwing signingKey needed

### ISSUE THREAD

**Issue by panterlo** [DotNetOpenAuth/DotNetOpenAuth#308] opened 2013-10-01 09:17 UTC
After using DotNetOpenAuth 5.1 master branched I bevlive I noticed a coding error in CreateFormatter changes from 4.3.1:

The method:

```
    internal static IDataBagFormatter<AccessToken> CreateFormatter(RSACryptoServiceProvider signingKey, RSACryptoServiceProvider encryptingKey) {
        Requires.That(signingKey == null || !signingKey.PublicOnly, "signingKey", "requires private key");

        return new UriStyleMessageFormatter<AccessToken>(signingKey, encryptingKey);
    }
```

This row:
            Requires.That(signingKey == null || !signingKey.PublicOnly, "signingKey", "requires private key");

seems to be incorrect:
            Requires.That(signingKey != null || !signingKey.PublicOnly, "signingKey", "requires private key");

Otherwise this method will always throw an error while trying to get the access token.

**Comment by AArnott** [comment] 2013-10-15 02:59
Duplicate of #298

**Closed as completed by AArnott** 2013-10-15 02:59 UTC
