### ISSUE TITLE
AccessToken CreateFormatter incorrect precondition on signingKey parameter

### ISSUE THREAD

**Issue by michael2m** [DotNetOpenAuth/DotNetOpenAuth#318] opened 2013-12-03 12:45 UTC
AccessToken.CreateFormatter(RSACryptoServiceProvider signingKey, RSACryptoServiceProvider encryptingKey)

has the following precondition:
    Requires.That(signingKey == null || !signingKey.PublicOnly, ...

The condition is incorrect. This issue prevents checking signatures with a public key (e.g. by resource server).

**Comment by AArnott** [comment] 2013-12-03 13:48
Duplicate of #298

**Closed as completed by AArnott** 2013-12-03 13:48 UTC
